# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Add use_modular_headers! here to apply globally
use_modular_headers!

target 'twinleaves' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Example for Firebase dependencies with :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

  target 'twinleavesTests' do
    inherit! :complete
    # Pods for testing
    pod 'Firebase/Core'
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Uncheck "Based on dependency analysis" for specific build phases
    installer.pods_project.targets.each do |target|
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:name)
          if build_phase.name == '[CP-User] [RNFB] Core Configuration' || build_phase.name == 'Bundle React Native code and images'
            build_phase.run_only_for_deployment_postprocessing = false
          end
        end
      end
    end
  end
end
